module.exports = {
  CREATE_LIBRARY: "CREATE_LIBRARY",
  UPDATE_LIBRARY: "UPDATE_LIBRARY",
  DELETE_LIBRARY: "DELETE_LIBRARY",
  CREATE_BOOK: "CREATE_BOOK",
  UPDATE_BOOK: "UPDATE_BOOK",
  DELETE_BOOK: "DELETE_BOOK",
  CREATE_STUDENT: "CREATE_STUDENT",
  ISSUE_BOOK: "ISSUE_BOOK",
  RETURN_BOOK: "RETURN_BOOK",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  PLAN_UPGRADE: "PLAN_UPGRADE",
  SETTINGS_UPDATE: "SETTINGS_UPDATE"
};
