const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  LIBRARY_ADMIN: "LIBRARY_ADMIN",
  LIBRARIAN: "LIBRARIAN",
  ASSISTANT: "ASSISTANT",
  STUDENT: "STUDENT",
  MEMBER: "MEMBER",
  BRANCH_MANAGER: "BRANCH_MANAGER"
};

module.exports = ROLES;
