const ROLES = require("./roles");
const PERMISSIONS = require("./permissions");

const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: [
    "*"
  ],
  [ROLES.LIBRARY_ADMIN]: [
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_BOOKS,
    PERMISSIONS.MANAGE_STUDENTS,
    PERMISSIONS.MANAGE_TRANSACTIONS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.MANAGE_SETTINGS,
    PERMISSIONS.VIEW_SECURITY
  ],
  [ROLES.LIBRARIAN]: [
    PERMISSIONS.MANAGE_BOOKS,
    PERMISSIONS.MANAGE_STUDENTS,
    PERMISSIONS.MANAGE_TRANSACTIONS,
    PERMISSIONS.VIEW_REPORTS
  ],
  [ROLES.ASSISTANT]: [
    PERMISSIONS.MANAGE_TRANSACTIONS
  ],
  [ROLES.STUDENT]: []
};

module.exports = ROLE_PERMISSIONS;
