import React from "react";
import { Link } from "react-router-dom";
import { useExportHistory } from "../../hooks/useExport";
import { DownloadCloud, CheckCircle, AlertTriangle, Clock, FileText, FileSpreadsheet } from "lucide-react";

const ExportHistory = () => {
  const { data, isLoading } = useExportHistory();
  const history = data?.data || [];

  return (
    <div className="p-6 max-w-6xl mx-auto">
      <div className="flex justify-between items-end mb-8">
        <div>
          <h1 className="text-2xl font-bold text-gray-800">Export History</h1>
          <p className="text-gray-500">Track all manual and scheduled exports generated by your team.</p>
        </div>
        <Link to="/export" className="bg-blue-600 text-white px-4 py-2 rounded font-medium hover:bg-blue-700 transition">New Export</Link>
      </div>

      {isLoading ? (
        <div className="text-center py-10 text-gray-400">Loading history...</div>
      ) : history.length === 0 ? (
        <div className="text-center py-20 bg-white border rounded-xl">
          <DownloadCloud size={48} className="mx-auto text-gray-300 mb-4" />
          <h3 className="text-lg font-bold text-gray-700">No Exports Yet</h3>
          <p className="text-gray-500 mt-2">You haven't generated any reports yet.</p>
        </div>
      ) : (
        <div className="bg-white border rounded-xl shadow-sm overflow-hidden">
          <table className="w-full text-left">
            <thead className="bg-gray-50 border-b border-gray-200 text-xs font-bold text-gray-500 uppercase tracking-wider">
              <tr>
                <th className="px-6 py-4">File Name</th>
                <th className="px-6 py-4">Module</th>
                <th className="px-6 py-4">Status</th>
                <th className="px-6 py-4">Created By</th>
                <th className="px-6 py-4">Date</th>
                <th className="px-6 py-4 text-right">Download</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {history.map((job) => (
                <tr key={job._id} className="hover:bg-gray-50">
                  <td className="px-6 py-4">
                    <div className="flex items-center gap-2">
                      {job.format === 'pdf' ? <FileText className="text-red-400" size={16} /> : <FileSpreadsheet className={job.format === 'xlsx' ? "text-green-500" : "text-blue-500"} size={16} />}
                      <span className="font-medium text-gray-900">{job.fileName}.{job.format}</span>
                    </div>
                  </td>
                  <td className="px-6 py-4">
                    <span className="bg-gray-100 text-gray-600 px-2.5 py-0.5 rounded text-xs font-bold uppercase">{job.type}</span>
                  </td>
                  <td className="px-6 py-4">
                    {job.status === 'COMPLETED' && <span className="inline-flex items-center gap-1 bg-green-100 text-green-800 px-2.5 py-0.5 rounded-full text-xs font-bold"><CheckCircle size={12}/> Ready</span>}
                    {job.status === 'FAILED' && <span className="inline-flex items-center gap-1 bg-red-100 text-red-800 px-2.5 py-0.5 rounded-full text-xs font-bold"><AlertTriangle size={12}/> Failed</span>}
                    {job.status === 'PROCESSING' && <span className="inline-flex items-center gap-1 bg-blue-100 text-blue-800 px-2.5 py-0.5 rounded-full text-xs font-bold"><Clock size={12}/> Generating</span>}
                    {job.status === 'PENDING' && <span className="inline-flex items-center gap-1 bg-gray-100 text-gray-800 px-2.5 py-0.5 rounded-full text-xs font-bold">Queued</span>}
                  </td>
                  <td className="px-6 py-4 text-sm text-gray-600">{job.createdBy?.firstName || 'System'}</td>
                  <td className="px-6 py-4 text-sm text-gray-500">{new Date(job.createdAt).toLocaleString()}</td>
                  <td className="px-6 py-4 text-right">
                    {job.status === 'COMPLETED' ? (
                      <a 
                        href={`${process.env.REACT_APP_API_URL}/v1/export/download/${job._id}`} 
                        download
                        className="text-blue-600 hover:text-blue-800 font-medium text-sm"
                      >
                        Download
                      </a>
                    ) : (
                      <span className="text-gray-300 text-sm">--</span>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
};

export default ExportHistory;
